CREATE TABLE IF NOT EXISTS integration_trace_events (
  id VARCHAR(64) PRIMARY KEY,
  trace_id VARCHAR(96) NOT NULL,
  parent_request_id VARCHAR(128) NOT NULL DEFAULT '',
  component VARCHAR(64) NOT NULL,
  stage VARCHAR(120) NOT NULL,
  status VARCHAR(24) NOT NULL,
  channel VARCHAR(24) NOT NULL,
  instance_id VARCHAR(64) NOT NULL DEFAULT '',
  sender_hash VARCHAR(128) NOT NULL DEFAULT '',
  session_key_hash VARCHAR(128) NOT NULL DEFAULT '',
  tool_name VARCHAR(100) NOT NULL DEFAULT '',
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  http_status INT NULL,
  business_code INT NULL,
  elapsed_ms BIGINT NULL,
  error_code VARCHAR(80) NOT NULL DEFAULT '',
  error_message VARCHAR(500) NOT NULL DEFAULT '',
  detail_json JSON NULL,
  created_at VARCHAR(40) NOT NULL,
  INDEX idx_trace_id_created(trace_id, created_at),
  INDEX idx_trace_filters(instance_id, channel, status, created_at),
  INDEX idx_trace_created(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
