CREATE TABLE IF NOT EXISTS model_call_audits (
  id VARCHAR(80) PRIMARY KEY,
  event_type VARCHAR(40) NOT NULL,
  instance_id VARCHAR(64) NOT NULL DEFAULT '',
  agent_id VARCHAR(128) NOT NULL DEFAULT '',
  session_id VARCHAR(128) NOT NULL DEFAULT '',
  session_key_hash CHAR(64) NOT NULL DEFAULT '',
  run_id VARCHAR(128) NOT NULL DEFAULT '',
  call_id VARCHAR(128) NOT NULL DEFAULT '',
  provider VARCHAR(120) NOT NULL DEFAULT '',
  model VARCHAR(200) NOT NULL DEFAULT '',
  api_transport VARCHAR(120) NOT NULL DEFAULT '',
  plugin_version VARCHAR(80) NOT NULL DEFAULT '',
  system_prompt LONGTEXT NULL,
  prompt LONGTEXT NULL,
  history_messages_json LONGTEXT NULL,
  images_count INT NOT NULL DEFAULT 0,
  output_text LONGTEXT NULL,
  usage_json LONGTEXT NULL,
  stop_reason VARCHAR(120) NOT NULL DEFAULT '',
  duration_ms BIGINT NULL,
  outcome VARCHAR(40) NOT NULL DEFAULT '',
  error_category VARCHAR(120) NOT NULL DEFAULT '',
  created_at VARCHAR(40) NOT NULL,
  expires_at VARCHAR(40) NOT NULL,
  INDEX idx_model_audit_instance_created (instance_id, created_at),
  INDEX idx_model_audit_session_created (session_key_hash, created_at),
  INDEX idx_model_audit_run_call (run_id, call_id),
  INDEX idx_model_audit_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
