CREATE TABLE IF NOT EXISTS agent_workspace_presets (
  id VARCHAR(32) PRIMARY KEY,
  version INT NOT NULL DEFAULT 0,
  agents_md MEDIUMTEXT NOT NULL,
  soul_md MEDIUMTEXT NOT NULL,
  identity_md MEDIUMTEXT NOT NULL,
  tools_md MEDIUMTEXT NOT NULL,
  heartbeat_md MEDIUMTEXT NOT NULL,
  user_md MEDIUMTEXT NOT NULL,
  updated_at VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
